# Generated by Django 3.1.5 on 2021-01-19 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='langguages',
            new_name='languages',
        ),
    ]
