# Generated by Django 3.1.5 on 2021-01-29 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resume', '0002_auto_20210119_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='Age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='resume',
            name='Phone',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
